// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import GalleriaController from "./galleria_controller"
application.register("galleria", GalleriaController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)

import TrixController from "./trix_controller"
application.register("trix", TrixController)
